version: '3'
services:
    web:
        container_name: web
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./srv:/srv
    php:
        container_name: php
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./srv:/srv
    mysql:
        container_name: mysql
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'template'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'template'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {} 